baseURL = 'https://morebetterfaster.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'mbf'
disableKinds = ["taxonomy", "term", "RSS"]

[menu]
[[menu.main]]
  name = 'Home'
  identifier = 'home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'Services'
  identifier = 'services'
  pageref = 'services'
  weight = 20
[[menu.main]]
  name = 'Code Review'
  pageref = 'services-code-review'
  weight = 21
  parent = 'services'
[[menu.main]]
  name = 'Development'
  pageref = 'services-development'
  weight = 21
  parent = 'services'
[[menu.main]]
  name = 'Projects'
  pageref = 'projects'
  weight = 30
[[menu.main]]
  name = 'About'
  pageref = 'about'
  weight = 40
[[menu.main]]
  name = 'Contact'
  pageref = 'contact'
  weight = 50