[[headers]]
  for = "/*"
  [headers.values]
    X-Security-Message= "Yup, we can help with that, too! :)"

[build]
  command = "npm --prefix=./themes/mbf install && hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.110.0"