[[headers]]
  for = "/*"
  [headers.values]
    X-You-Are = "A nerd... :)"

[[redirects]]
  from = "https://morebetterfaster.netlify.com/*"
  to = "https://morebetterfaster.io/:splat"
  status = 301

[[redirects]]
  from = "https://morebetterfaster.netlify.app/*"
  to = "https://morebetterfaster.io/:splat"
  status = 301
